### PR TITLE
Adds ab-memberonly to config

### PR DESCRIPTION
**Pull request by LJWatson**

### CODE REVIEW

**Comment by LJWatson** [comment]
Relates to w3c/ab-memberonly#21

**Comment by dbaron** [comment]
So presumably this would work by giving the bot (and thus me) access to the `#ab` IRC channel?  Is that desired?

I'd note that right now the bot is set up in a way that I can trivially read the traffic on the channels it is on (which is useful both for debugging and for determining whether it's an ok time to restart the bot).  I could change that... but at that point you'd just be trusting me to tell you how it's set up, I guess?

**Comment by LJWatson** [comment]
The channel isn't presently protected and the meetings are shared with 
the AC after the fact, but to be on the safe side I'll ask the AB for 
clear consent.

**Comment by LJWatson** [comment]
The AB has agreed to let the bot, and by proxy you, have access to the AB IRC channel, but asks that you maintain AB confidentiality should you need to look at the channel traffic for any reason.

If at all possible we'd like to try using the bot at our F2F this week, which starts tomorrow 8.30am ET. If you don't have time, it's not a problem though.

**Comment by dbaron** [comment]
OK, the bot should be restarted now and in the `#ab` channel.

It's possible you may need to do something on the github side to give the bot permission to see and/or comment on issues, so it might be worth testing it out with a real issue before the face-to-face starts.

**Comment by LJWatson** [comment]
Thank you David.

The bot is present and correct, but as you surmised we just need to give 
it permission to post to the relevant repo.

**Pull request merged**
